#targets:
#  $default:
#    builders:
#      repo_generation:
#        enabled: true
#
#builders:
#  repo_generation:
##    target: ":repo_generation"
#    import: "package:repo_generation/builder.dart"
#    builder_factories: [ "subclassGen", "extGen" ]
#    build_extensions: { ".dart": [ ".g.dart" ] }
#    auto_apply: dependents
#    build_to: cache
#    applies_builders: ["source_gen|combining_builder"]



targets:
  $default:
    builders:
      repo_generation:
        enabled: true

builders:
  repo_generation:
    import: "package:repo_generation/builder.dart"
    builder_factories: ["extGen", "subclassGen"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]