name: repo_generation
description: A new Flutter project.
version: 0.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^4.0.0
  build_config: ^1.2.0
  code_builder: ^4.11.0
  better_repo_annotation: ^0.0.3
  source_gen: ^4.0.1
  analyzer: ^8.1.1

dev_dependencies:
  build_test: ^3.4.0
  build_runner: ^2.8.0



